from ext import app, db
from models import Post, User, Event, ReadPost

with app.app_context():
    db.create_all()

    events = [
        {"image_path": "basketball_invented.png", "year": 1891, "title": "Basketball is Invented",
         "short_description": "Dr. James Naismith creates basketball with a peach basket and a soccer ball.",
         "title_one": "Where Basketball Originated",
         "text_one": "It was the winter of 1891-1892. Inside a gymnasium at Springfield College (then known as the International YMCA Training School), located in Springfield, Mass., was a group of restless college students. The young men had to be there; they were required to participate in indoor activities to burn off the energy that had been building up since their football season ended. The gymnasium class offered them activities such as marching, calisthenics, and apparatus work, but these were pale substitutes for the more exciting games of football and lacrosse they played in warmer seasons.",
         "title_two": "James Naismith, The Person Who Invented Basketball",
         "text_two": "The instructor of this class was James Naismith, a 31-year-old graduate student. After graduating from Presbyterian College in Montreal with a theology degree, Naismith embraced his love of athletics and headed to Springfield to study physical education—at that time, a relatively new and unknown academic discipline—under Luther Halsey Gulick, superintendent of physical education at the College and today renowned as the father of physical education and recreation in the United States. As Naismith, a second-year graduate student who had been named to the teaching faculty, looked at his class, his mind flashed to the summer session of 1891, when Gulick introduced a new course in the psychology of play. In class discussions, Gulick had stressed the need for a new indoor game, one “that would be interesting, easy to learn, and easy to play in the winter and by artificial light.” No one in the class had followed up on Gulick’s challenge to invent such a game. But now, faced with the end of the fall sports season and students dreading the mandatory and dull required gymnasium work, Naismith had a new motivation.",
         "title_three": "",
         "text_three": "Naismith later wrote that he had expressed his opinion that “the trouble is not with the men, but with the system that we are using.” He felt that the kind of work needed to motivate and inspire the young men he faced “should be of a recreative nature, something that would appeal to their play instincts.” So Naismith went to work. His goal was to create a game that would be simple to understand but complex enough to be interesting. The game had to be playable indoors, and it had to accommodate several players at once. The game also needed to provide plenty of exercise for the students, yet without the physicality of football, soccer, or rugby since those would threaten more severe injuries if played in a confined space. Much time and thought went into this new creation, as it incoprorated details from the sports mentioned above, as well as eomthing called duck on a rock, a game Naismith had played with his childhood friends in Bennie’s Corners, Ontario. Duck on a rock used a ball and a goal that could not be rushed. The goal could not be slammed through, thus necessitating “a goal with a horizontal opening high enough so that the ball would have to be tossed into it, rather than being thrown.” ",
         "title_four": "",
         "text_four": "Naismith approached the school janitor, hoping he could find two square boxes to use for goals. When the janitor came back from his search, he had two peach baskets instead. Naismith nailed the peach baskets to the lower rail of the gymnasium balcony, one on each side. The height of that lower balcony rail happened to be 10 feet. The students would play on teams to try to get the ball into their team’s basket.  A person was stationed at each end of the balcony to retrieve the ball from the basket and put it back into play. It wasn’t until a few years later that the bottoms of those peach baskets were cut to let the ball fall loose. Naismith then drew up the 13 original rules, which described, among other facets, the method of moving the ball and what constituted a foul. A referee was appointed. The game would be divided into two, 15-minute halves with a five-minute resting period in between. Naismith’s secretary typed up the rules and tacked them on the bulletin board. A short time later, the gym class met, and the teams were chosen with three centers, three forwards, and three guards per side. Two of the centers met at mid-court, Naismith tossed the ball, and the game of “basket ball” was born.",
         "read_more": "Springfield.edu: https://shorturl.at/vy5Lo;   National Geographic: https://shorturl.at/g0cLP;   Britannica: https://shorturl.at/YtTyp",
         },
        {"image_path": "first_womens_match.png", "year": 1893, "title": "First Women’s Basketball Game", "short_description": "The first-ever women’s basketball game is played at Smith College, paving the way for women in the sport.",
         "title_one": "Where Did It Happen",
         "text_one": "On March 22, 1893, the first women’s college basketball game was played at Smith College (a historically women’s college in Northampton), Massachusetts. The game was played according to the rules of Athletic Director Senda Berenson. Her rules included: playing for two fifteen minute halves, dividing the court into three sections and requiring the players to stay within their assigned area, limiting the amount of time players could hold the ball, and limiting the players to only three dribbles at a time to encourage passing. Every basket earned the team one point. With each made basket counting as one point and the game lasting two 15-minute halves, eventually, a sophomore class team prevailed over a freshmen team, 5-4, earning a gold and white banner. Men were not permitted inside the gym at the all-women college, but a crowd of fascinated women cheered on their fellow classmates from the running track of the campus gymnasium.",
         "title_two": "Who was Senda Berenson?",
         "text_two": "Senda Berenson Abbott was the “Mother of Women’s Basketball.” As the director of physical education at Smith College in Northampton, Massachusetts, Berenson Abbott incorporated the same concepts James Naismith had developed for men into an exercise regime for her all-female classes - she actually learned the game of basketball from Dr. James Naismith less than two years after he initially developed the game in 1891 in Springfield, Massachusetts, and adapted her rules for women in order to limit physical contact and reduce overall physical exertion. Berenson’s rules for basketball quickly spread to other women’s colleges across the country and the sport of women’s college basketball flourished, the first intercollegiate game taking place in 1896.",
         "title_three": "",
         "text_three": "Like Naismith, she stressed socialization and cooperation rather than competition. Since vigorous exercise for women was thought unhealthy, she divided the court into three sections and required players to stay in their assigned section. From the time the first game was held at Smith, when no male spectators were even allowed, Berenson Abbott poured her energy, passion, and dedication into improving women's basketball. Author and founder of the first Basketball Guide for Women, she chaired the Women’s Basketball Committee for twelve years and continued to edit her rules guidebook throughout her life. While Berenson’s version of basketball, with its rules meant to encourage womanliness and ladylike deportment, was eventually put aside in favor of a version with rules almost identical to the men’s game, Berenson’s mark on basketball has not been forgotten.",
         "title_four": "",
         "text_four": "When the WNBA was formed in 1996, the league paid homage to this first ever women’s game at Smith College and its inventor, Senda Berenson. In a commemorative program released to celebrate the WNBA’s first season, Berenson was named as the first among women’s basketball pioneers and in a timeline of women’s basketball history, she was given the first slot. Berenson, who died in 1954, was enshrined in the Naismith Basketball Hall of Fame as a contributor in 1985. She was inducted into the Women’s Basketball Hall of Fame in 1999.",
         "read_more": "History.com: https://shorturl.at/T7RbA;   Zinn Education Project: https://shorturl.at/Su8TK;   Basketball Hall of Fame: https://shorturl.at/1WpbE",
         },
        {"image_path": "olympic_debut.png", "year": 1936, "title": "Basketball Debuts in the Olympics",
         "short_description": "Basketball becomes an official Olympic sport at the Berlin Games, marking its international rise.",
         "title_one": "When Did Basketball Become an Olympic Sport",
         "text_one": "Basketball was introduced in the Olympic programme at the 1904 Games in St Louis as a demonstration event. Basketball was first contested as a medal event at the 1936 Olympics. Women’s basketball, meanwhile, made its debut at the Montreal 1976 Games. The United States of America is the most successful team in the history of Olympics basketball. The USA Olympic men’s basketball team has won the gold medal a record 17 times, which includes an unbeaten streak from 1936 to 1968. The USA women’s basketball team, meanwhile, has pocketed the gold medal on 10 occasions. This includes an unbeaten run that’s still in place and dates back to Atlanta 1996.",
         "title_two": "USA's basketball at the Olympics",
         "text_two": "Having invented the sport in the late 1800s, it was no surprise that the USA dominated basketball once it was included as a medal event at the 1936 Olympics. With the Young Men’s Christian Association (YMCA) playing a key role in spreading the sport to various nations, as many as 21 teams competed for the top honours at the Berlin 1936 Games. But none could stand in the USA’s way as they romped home to emphatic wins in each of their matches to take home the gold.",
         "title_three": "Fun Facts on Olympic Basketball",
         "text_three": "1. A soccer ball was first used in basketball before switching to the orange/brown basketball we use today; 2. Before metal hoops with backboards were used starting in the early 1900s, peach baskets with holes drilled in the bottom were used as the hoops.; 3. A Massachusetts YMCA instructor invented basketball so students could have an indoor sport to play during the winter.",
         "title_four": "",
         "text_four": "",
         "read_more": "Olympics.com: https://shorturl.at/F8d3L, https://shorturl.at/PnvTI", },
        {"image_path": "nba_founded.png", "year": 1946, "title": "NBA is Founded",
         "short_description": "The Basketball Association of America (BAA) merges with the National Basketball League (NBL) to form the NBA.",
         "title_one": "National Basketball Association",
         "text_one": "By the 1940s, basketball was one of America’s most popular sports. People of all ages played the game, and college teams had fans across the nation. Professional basketball, however, received little attention. Pro hoops had many teams and leagues, but few fans. Pro basketball finally hit the big time on November 1, 1946. On that date, the National Basketball Association played its first game. The NBA looked a lot different then. For one thing, it was called the Basketball Association of America (it became the NBA in 1949). The jump shot was new. Most shooters kept both feet on the floor. The players were not as tall as today’s stars. In addition, the NBA did not have any African-American players until its fifth season (1950-51). The NBA had 11 teams in its first season. Three of those franchises are still playing: the Boston Celtics, the Golden State Warriors, and the New York Knicks. The Warriors, then based in Philadelphia, won the first NBA Finals in 1947. The NBA struggled to survive those early years. The games had too many fouls and too few points. Many teams folded. In the 1950s, rule changes cut down on rough play. Then, in 1954, the League introduced the 24-second shot clock, and scoring took off. The NBA has been soaring ever since.",
         "title_two": "League growth and membership",
         "text_two": "Professional basketball league formed in the United States in 1949 by the merger of two rival organizations, the National Basketball League (founded 1937) and the Basketball Association of America (founded 1946). In 1976 the NBA absorbed four teams from the American Basketball Association (ABA), which disbanded that year. By the early 1980s the NBA was plagued by money-losing franchises, low attendance, declining television ratings, and limited national appeal. The league soon rebounded under the leadership of David Stern, NBA commissioner from 1984, who helped transform it into an international entertainment company. Aggressive marketing highlighted star players such as Magic Johnson, Larry Bird, and, especially, Michael Jordan. Other innovations included league limits on player salaries, lucrative broadcast rights for network and cable television, and expanded All-Star Game festivities.",
         "title_three": "",
         "text_three": "",
         "title_four": "",
         "text_four": "",
         "read_more": "Britannica: https://shorturl.at/kv3ep; jr.nba.com: https://shorturl.at/nACNw;",},
        {"image_path": "shot_clock.png", "year": 1954, "title": "Shot Clock Introduced",
         "short_description": "The NBA introduces the 24-second shot clock to speed up the game and boost excitement.",
         "title_one": "The Clock Starts Ticking",
         "text_one": "By the end of the 1953-54 season, a plague was infesting the N.B.A. Slow, boring, foul-riddled, low-scoring games became commonplace as teams sat on the ball. Such talented guards as Bob Cousy would, if their team had a lead in the fourth quarter, simply kill time by dribbling in the backcourt until they were fouled. It was not uncommon for at least five minutes to pass without a shot being taken from the field.",
         "title_two": "",
         "text_two": "The Fort Wayne Pistons decided to combat the two-time reigning NBA champion Minneapolis Lakers, led the league’s first superstar George Mikan, with a stall technique. The Pistons, who would hold the ball for as long as four minutes on some possessions, won 19-18 in the lowest-scoring game in league history. Commissioner Maurice Podoloff sent a letter to all teams letting them know that this kind of game was to never happen again because it would kill the league. Sure enough, per-game attendance dropped for the next three years. At the NBA’s annual owner’s meeting, Syracuse Nationals owner Danny Biasone – an Italian immigrant who owned a bowling alley and a restaurant and acquired a National Basketball League franchise for $1,000 and then saw the league merge with the Basketball Association of America and become the NBA – proposed a 24-second shot clock. The solution, Danny Biasone was convinced, was a limit on the time each team had to shoot. 'So I went to those fellas in the league and said I'm having a tough time selling something here,' he recalled. 'There's one thing basketball needs, I said. It needs a time. I don't care what the time is. Put in a time!' ",
         "title_three": "",
         "text_three": "The clock was based on the logic that teams averaged 60 shots per game. Given that the players could use the entire time to shoot, Biasone figured teams might still average 60 shots per game, but play a faster and more exciting brand of basketball. The year prior to the shot clock, NBA teams averaged 79.5 points a game. With the implementation of the new device, teams averaged 93.1 points a game and the number of field goals attempted climbed from 75.4 to 86.4. Speeding up the game meant more than just higher scores. Fan interest soared and the NBA was on its way to better days. Biasone owned the Syracuse Nationals from1946 to 1963 and won the NBA championship in 1955.",
         "title_four": "",
         "text_four": "When the Rochester Royals played the Boston Celtics to open the season on Oct. 30, the 24-second clock was an official N.B.A. rule. At that time, considered as 'the most important man in the N.B.A.' still went into the bowling alley he had owned for years, the Eastwood Sports Center, every day. He played golf, was still a 'sports nut,' and he still wished he was in pro basketball. Although he has received a 'special citation,' he is not, shamefully, an official member of basketball's Hall of Fame.",
         "read_more": "The New York Times: https://shorturl.at/nSHBh; Basketball Hall of Fame: https://shorturl.at/mz2RK; The Denver Gazette: https://shorturl.at/265ry",},
        {"image_path": "bill_russell.png", "year": 1956, "title": "Bill Russell Drafted",
         "short_description": "Bill Russell joins the Boston Celtics, leading them to 11 championships and defining the modern dynasty.",
         "title_one": "Bill Russel's Biography",
         "text_one": "William 'Bill' Felton Russell was born February 12, 1934 in West Monroe, LA, and attended McClymonds High School after his family moved to Oakland, CA when he was eight years old. In his early years, he was a runner and a track jumper, and was cut from the basketball team at Herbert Hoover Junior High School. Struggling to learn the necessary skills for basketball, he was nearly cut from his high school team, but his coach encouraged him to work on his fundamentals, and he accepted that challenge. Coupled with a growth spurt, he started to improve his defense by learning to jump to make and block shots, which was not mainstream at the time. In high school, he began studying the footwork and court plays of other players in order to improve his floor skills.",
         "title_two": "",
         "text_two": "Despite being an All-Conference in high school, he was overlooked by most college recruiters. His only scholarship opportunity was with USF, and Russell accepted. His talent blossomed on the Hilltop as he established a legacy of excellence due to his defensive skills, shot-blocking and rebounding. He combined the speed of a guard with the skills of a center. Before Bill Russell brought his marvelous defensive and shot-blocking skills to basketball, the game focused primarily on offense. Russell reversed the trend, initiating a defensive mentality that remains a focal part of championship basketball. Considered the greatest defensive center in basketball history, the agile Russell was a dominant collegian. Playing under Hall of Fame Coach Phil Woolpert, and with fellow Hall of Famer K.C. Jones, Russell helped the University of San Francisco become one of college basketball's most exciting and prosperous teams. Russell then turned the Boston Celtics into a powerful machine that overwhelmed opponents both defensively and offensively.",
         "title_three": "",
         "text_three": "He was named Street and Smith’s fourth greatest college basketball player, and was drafted by the Saint Louis Hawks in 1956, in Round 1 (2nd pick overall). The Hawks eventually gave up Russell to the Celtics in exchange for Macauley and Cliff Hagan. During that same draft, coach Red Auerbach also drafted K.C. Jones, Russell’s former teammate, and then had three future Hall of Fame players in Russell, Jones and Tommy Heinsohn. During his first game, rookie Russell impressed the Boston fans with his man-to-man defense and his shot-blocking. Russell was so quick that he could run over to assist in a double team and then make it back to find the open man. The Celtics played aggressively and Russell’s blocks were called “Wilson-burgers,” referring to the Wilson brand ball he shoved into the faces of his shooting opponents. The Celtics finished their season with a 44-28 record. During Russell's career, Boston won eleven NBA championships, including eight consecutive titles from 1959 to 1966. Russell's head-to-head battles with Wilt Chamberlain were legendary. Russell was a five-time league MVP (1958, 1961-63, 1965), 12-time NBA All Star, Sports Illustrated Sportsman of the Year (1968), and The Sporting News Athlete of the Decade (1970). The Celtics retired his jersey (#6).",
         "title_four": "",
         "text_four": "In 1966, Coach Auerbach retired, and Russell became a Player-Coach and eventually Head Coach later that year, the first black head coach in NBA history. In his first full season, the Celtics winning streak ended in a game against the Philadelphia 76ers who were led the legendary Wilt Chamberlain. After their loss, Russell congratulated his longtime opponent and friend, and then led his grandfather back to the Celtics locker room where his grandfather saw a white and black player showering next to each other, discussing the game. His grandfather broke down in tears with pride that his grandson was the coach of a team where players of all races coexisted in harmony. During the final three seasons of his career, Russell served as player-coach of the Celtic, once again paving the way as he became the first black NBA Coach­ and the first to win the NBA Championship. He left his position after winning the 1969 NBA Championship and the following year the team sunk to a 34-48 record. The Celtics had failed to make the NBA playoffs for the first time since 1950. ",
         "read_more": "Basketball Hall of Fame: https://shorturl.at/yivnH; University of San Francisco Athletics: https://shorturl.at/vCUIi; BRitannica: https://shorturl.at/R8Z90",},
        {"image_path": "aba.png", "year": 1967, "title": "ABA is Created (Birth of the Three-Point Line)",
         "short_description": "The rival ABA league introduces the flashy three-point line, which later changes the NBA forever.",
         "title_one": "American Basketball Association",
         "text_one": "former professional basketball league formed in the United States in 1967 to rival the older National Basketball Association (NBA). George Mikan, a former star player in the NBA, was the ABA’s first commissioner. The ABA fielded 11 teams in its first season and quickly earned a loyal following with its wide-open style of play. The league introduced a number of rule changes, most notably the three-point shot and a red, white, and blue ball. The quality of play was equal to that of the NBA, and the ABA nurtured the careers of Julius (“Dr. J”) Erving, Connie Hawkins, and David Thompson.",
         "title_two": "",
         "text_two": "A proposed merger between the ABA and the NBA was met with a class action suit filed by ABA players, who alleged violations of antitrust laws. The settlement in 1976 resulted in the dissolution of the ABA, with four ABA teams—the New York Nets, the Denver Nuggets, the San Antonio Spurs, and the Indiana Pacers—absorbed into the NBA, a dispersal draft of certain ABA players by NBA teams, and the remaining players granted permission to act as free agents.",
         "title_three": "",
         "text_three": "",
         "title_four": "",
         "text_four": "",
         "read_more": "Britannica: https://shorturl.at/RkCvN; ",},
        {"image_path": "nba_aba_merger.png", "year": 1976, "title": "NBA & ABA Merge",
         "short_description": "The NBA absorbs four ABA teams, bringing dunking and fast-paced play to the league.",
         "title_one": "The ABA-NBA Merger: A Game-Changing Moment in Basketball History",
         "text_one": "The merger between the American Basketball Association (ABA) and the National Basketball Association (NBA) in 1976 stands as a watershed moment in professional basketball history. This significant event not only reshaped the landscape of the sport but also left a lasting legacy that continues to influence the game today. Let's delve into the circumstances that led to this historic merger and its profound impact on the world of basketball.",
         "title_two": "The Birth of the ABA",
         "text_two": "The ABA was founded in 1967 as a rival to the NBA, bringing a fresh, innovative approach to the sport. Known for its flashy style of play, colorful basketballs, and the introduction of the three-point line, the ABA quickly carved out a niche for itself. The league attracted top talent, including future legends like Julius 'Dr. J' Erving, George Gervin, and Moses Malone, by offering competitive salaries and a more freewheeling style of play.",
         "title_three": "The Rivalry and Its Challenges",
         "text_three": "For nearly a decade, the ABA and NBA competed for fans, players, and market share. While the ABA introduced exciting changes and a more dynamic style of play, it struggled with financial instability, team relocations, and overall league viability. The NBA, though more stable, faced the challenge of maintaining its dominance in the face of the ABA’s growing popularity and innovation. By the mid-1970s, both leagues recognized the benefits of unification. The ABA's financial troubles made it difficult to sustain operations independently, while the NBA saw an opportunity to consolidate talent and expand its market reach. After extensive negotiations, the two leagues agreed to merge in 1976, with the NBA absorbing four ABA teams: the Denver Nuggets, Indiana Pacers, New York Nets, and San Antonio Spurs. The remaining ABA teams were disbanded, and their players were either absorbed by NBA teams or entered into a dispersal draft.",
         "title_four": "Key Elements of the Merger",
         "text_four": "Team Integration: The merger brought the Nuggets, Pacers, Nets, and Spurs into the NBA, preserving the legacy and fan bases of these franchises. Player Assimilation: ABA stars were integrated into the NBA, elevating the level of competition and introducing new styles of play. Rule Changes: The NBA adopted several ABA innovations, most notably the three-point line, which has become a fundamental aspect of modern basketball. Expansion of Market: The merger expanded the NBA's reach, bringing professional basketball to new cities and broadening its national appeal. The ABA-NBA merger had several long-lasting effects: Elevated Competition: The infusion of ABA talent raised the overall level of play in the NBA, leading to more exciting and competitive games. Innovative Play: The three-point line and other ABA-inspired innovations brought a new dimension to the game, changing how basketball was played and watched. Cultural Influence: The merger helped popularize a more flamboyant, high-flying style of play, which became a hallmark of the NBA’s identity. Financial Growth: By consolidating resources and markets, the NBA strengthened its financial stability and set the stage for future expansion and growth.",
         "read_more": "Linkedin.com: https://shorturl.at/wZrrq",},
        {"image_path": "three_pointer.png", "year": 1979, "title": "NBA Introduces Three-Point Line",
         "short_description": "The NBA officially adds the three-point line, changing offensive strategy forever.",
         "title_one": "History of the 3-Pointer",
         "text_one": "On November 13, 1967, the Indiana Pacers of the American Basketball Association were losing to the Dallas Chaparrals, 118-116, with just one second left on the clock. Indiana inbounded the ball to Jerry Harkness, who was 92 feet away from the basket. With no time to do anything else, Harkness threw a towering Hail Mary heave toward the goal. It smacked off the backboard and went in. Pandemonium erupted in Dallas, but for all the wrong reasons. You see, 1967 was the first year of the 3-point shot among basketball's top leagues, and the players and fans weren't used to it. A lot of the 2,500 in attendance that day thought that the Harkness miracle tied the game and forced overtime. In fact, he was 68 feet behind the brand new 3-point line. His shot won the game for the Pacers, 119-118. 'We were running off the floor to huddle up for the overtime when the official, Joe Belmont, came up to me and said 'Jerry, it's over. That was a 3-pointer,'' Harkness said in the book Loose Balls. 'I said, 'I forgot all about that. A 3-pointer.' Then we were celebrating again, because we found out that we won the game. 'These days, the 3-pointer is second-nature to basketball players and fans. It's a safe bet that nobody under the age of 30 has any recollection of college or professional basketball being played without a 3-point line.",
         "title_two": "The Inception",
         "text_two": "The 3-point line's first use in a professional league was back in 1961 in the American Basketball League. The ABL only lasted 1 ½ seasons before folding, so the 3-pointer quickly went away. The NBA, which had been around since 1946, never seriously considered it at that point. But when a new league competing against the NBA was dreamed up in the mid-1960s, the 3-point shot was back in the spotlight. The ABA, which started in 1967, differed from the NBA in its experimentation of fan-friendly ideas. They had a red, white and blue basketball, a slam dunk contest, and of course, the 3-point shot.",
         "title_three": "",
         "text_three": "According to the book Loose Balls: The Short, Wild Life of the American Basketball Association, which chronicled the nine-season history of the ABA, league organizers had planned to use the 3-pointer from the beginning. Coincidentally, the commissioner of the ABA and a big proponent of the 3-pointer was George Mikan, a 6-foot-10 NBA legend who probably would've never shot one during his playing days. 'We called it the home run, because the 3-pointer was exactly that,' Mikan said in the book. 'It brought fans out of their seats. ' In 1976, the ABA and NBA merged, with four teams joining the NBA--the Indiana Pacers, San Antonio Spurs, Denver Nuggets and New Jersey Nets. The 3-point shot, at first, wasn't part of the package. The NBA stayed firm in the game's traditions. The league didn't adopt the 3-pointer until 1979--Magic Johnson and Larry Bird's rookie season. While certain college basketball conferences experimented with it in the early '80s, the NCAA didn't universally implement a 3-point line until 1986, with high school basketball following suit a year later.",
         "title_four": "The Adjustment",
         "text_four": "In the late 1960s, when the ABA introduced the 3-pointer, a generation of coaches had to rethink everything they knew about the game, and it made things hectic. One ABA coach admits that at first, he never used the 3-pointer unless his team was losing late in the game and was desperate for points. 'It took a while for players to understand time and score situations, when to take it,' said Len Elmore, who played in both the ABA and NBA. 'You also recognize that players who hadn't been accustomed to playing with a 3-point line really had to work to develop the range.' Michael Jordan is a perfect example of that. He played college basketball at North Carolina without a 3-point line. In his rookie season with the Chicago Bulls, he was 9-for-52 from 3-point range. He never shot better than 20 percent from long range until his fifth season in the NBA. But by the time his remarkable tenure with the Bulls wrapped up, he was consistently shooting better than 35 percent from 3-point range. More than anything, though, the 3-point line has made basketball a completely different experience for the fans--a more spread-out game with another level of energy that wasn't there before the 1960s.",
         "read_more": "usab.com: https://shorturl.at/xNEDW",},
        {"image_path": "magic_vs_bird.png", "year": 1980, "title": "Magic vs. Bird Rivalry Begins",
         "short_description": "Magic Johnson and Larry Bird revolutionize the NBA with their legendary Lakers-Celtics battles.",
         "title_one": "Bird & Magic, Best Of Frenemies",
         "text_one": "Starting in the late 1970s, Larry Bird and Magic Johnson did legendary battles on the basketball court, first electrifying the NCAA’s March Madness tournament and then igniting a beleaguered NBA. Before they were enemies, they were All-American teammates for 5 days, thrust against teams from the Soviet Union, Cuba, and Yugoslavia at the 1978 World Invitational Tournament. At the time, Bird and Magic were second-stringers on the U.S. squad. But few predicted the duo would soon explode as college stars, professional rivals, and later on, close friends. That odyssey only added to their lore.",
         "title_two": "The unlikely basketball journey of two stars",
         "text_two": "A dazzling African-American hoopster with an infectious smile and an outgoing personality, Earvin Johnson, Jr. got his “Magic” nickname from a local reporter who was enthralled by his dynamic ball handling skills. Johnson grew up in Lansing, Michigan in a busy household with 6 siblings and was influenced by his parents’ strong work ethic. His father was employed at a GM plant and his mother was a school janitor. Magic’s future nemesis couldn’t be any different except for displaying the same drive for winning on the basketball court. A quiet white kid from French Lick, Indiana, Bird was slow and flat-footed, but a tough competitor and an undeniable shooting wizard. Bird’s early years in rural Indiana were fraught with family problems and financial hardships. His parents divorced when he was in high school and his mother worked 2 jobs to support him and his 5 siblings. His father committed suicide a year after the divorce.",
         "title_three": "An Intense Rivalry",
         "text_three": "Brought together under unlikely circumstances, the two were now facing each other at the 1979 NCAA Division I Championship, Magic as a sophomore point guard for Michigan State and Bird as a senior forward for Indiana State. The young prodigies lit up TV screens across the country and helped transform the tournament into the hottest sports property for CBS. ESPN network was founded the following year on that success. At the 1979 Regional Finals, Indiana State defeated Arkansas with just a 2-point margin (73-71) before overcoming DePaul at the Final Four in an equally tight game (76-74). The Indiana native ended up succumbing to Magic, who picked up the Most Outstanding Player award for the series. It was the beginning of the Bird and Magic feud, which would carry into the NBA. - The following season, Bird went east to join the Boston Celtics (1st Round/6th Pick) and Magic headed west for the Los Angeles Lakers (1st Round/1st Pick). With their basketball journeys intertwined, they became the darlings of the sports media who exploited their rivalry to boost ratings. The Celtics and Lakers weren’t strangers, as the two coastal franchises had confronted each other six times at the Finals during their dynastic heydays of the 1960s. - In the pro championships, Bird and Magic locked horns three times- 1984, 1985, 1987- cementing the Celtics-Lakers rivalry as the greatest in basketball. After hoisting the trophy with the Celtics in 1984, Bird felt vindicated from his loss to Magic in college. Though, Johnson and the lakers would claim the other two for a 2-1 career favor",
         "title_four": "Lifelong Friendship",
         "text_four": "At the 2019 NBA Lifetime Achievement Award, Bird and Magic stood side-by-side, even holding each other’s awards, as they were honored for their dual contributions to the game. But race was never an issue for the two luminary athletes who just wanted to play basketball and win games. Focused and disciplined, both averted the pitfalls of youth that could have sent them into dead-end, troubled lives. In the summer of 1985, seeing the combined marketing potential of Bird and Magic, Converse featured them in a sneaker commercial that was shot outside the home of Bird’s mother in Indiana. Skeptical at first about appearing together, they ended up bonding over lunch in the kitchen of Bird’s mother, planting the seed of a life-long friendship. That relationship grew even closer after Magic tested positive for the HIV virus in November, 1991. Bird’s empathy and support in an era when HIV was a stigma on men, especially as seen by other NBA players, made Magic realize who his close friends were. At Magic’s Hall of Fame induction ceremony in 2002, Bird (inducted in 1998) gave the introductory speech and stood on stage with Magic’s family as his close friend and old rival delivered a wistful talk to a packed audience.",
         "read_more": "NBA.com: https://shorturl.at/o8MSn; sportshistoryweekly.com: https://shorturl.at/u9Lgc",},
        {"image_path": "jordan_drafted.png", "year": 1984, "title": "Michael Jordan Enters NBA",
         "short_description": "Michael Jordan is drafted by the Chicago Bulls.",
         "title_one": "College Career",
         "text_one": "Jordan enrolled at North Carolina in 1981 and soon became an important member of the university’s basketball team. UNC won the NCAA Division I championship in 1982, with Jordan scoring the final basket needed to defeat Georgetown University. He was also singled out as the NCAA College Player of the Year in 1983 and in 1984. Jordan left college after his junior year to join the NBA in 1984. In 1986, Jordan finished his bachelor’s degree in geography as he continued to play basketball professionally.",
         "title_two": "Professional Basketball Career",
         "text_two": "The 6-foot-6 Jordan began his professional basketball career when he was drafted by the Chicago Bulls in 1984. He was the third overall pick, behind Hakeem Olajuwon, who was selected first by the Houston Rockets, and Sam Bowie, taken by the Portland Trail Blazers; the draft also featured legendary players John Stockton and Charles Barkley. Jordan soon proved himself on the court. He helped the Bulls make the playoffs and scored an average of 28.2 points per game that season. For his efforts, Jordan received the NBA Rookie of the Year Award and was selected for the All-Star Game. Although his second season was marred by injury, he broke new ground on the court during the 1986-87 season. He became the first player since Wilt Chamberlain to score more than 3,000 points in a single season. By the late 1980s, the Chicago Bulls were quickly becoming a force to be reckoned with, and Jordan was an instrumental part of the team’s success.",
         "title_three": "",
         "text_three": "Michael Jordan personified greatness on the court, and redefined superstar athlete off it. His freshman season at UNC culminated with Jordan hitting the game-winning shot in the 1982 NCAA national title game. That shot put Michael on the map and a new era was born. Following his junior year, Jordan entered the NBA Draft and was selected third overall by the Chicago Bulls. The young superstar began stockpiling NBA hardware. The court was his and the world soon followed. His unmistakable style - the wagging tongue, the baggy shorts, the signature line of sneakers - helped make the 14-time All Star the most recognizable person on the planet. Still his resume lacked an NBA title. Then in 1991, the Jordan-led Bulls launched an all-out assault on the rest of the league winning three straight world championships. Michael won Olympic gold again in 1992 and then in 1993 abruptly retired from the Bulls to play minor league baseball. He returned to the NBA full-time in 1995 and the Bulls promptly won three consecutive titles. Jordan was named Finals MVP each time. In 2001, Jordan made a second improbable comeback and still averaged 20 points per game and appeared in the 2002 and 2003 All Star Games.",
         "title_four": "Olympics, Awards and Honors",
         "text_four": "During the summer of 1984, Jordan made his first appearance at the Olympic Games as a member of the U.S. Olympic basketball team. The team of college amateurs won the gold at the games that year, which were held in Los Angeles. Jordan later helped the American team bring home the gold medal at the 1992 Olympic Games, held in Barcelona, Spain. The U.S. squad featured professional players for the first time that year, including Larry Bird, Magic Johnson, and Jordan, and became known as the “Dream Team.”. In 1988, Jordan received his first MVP Award from the NBA, an honor he would earn four more times, in 1991, 1992, 1996, and 1998. Advertisement - Continue Reading Below In April 2009, Jordan received one of basketball’s greatest honors: He was inducted into the Naismith Memorial Basketball Hall of Fame. Attending the induction ceremony was a bittersweet affair for Jordan because being at the event meant “your basketball career is completely over,” he explained. In 2016, Jordan was presented with the Presidential Medal of Freedom by President Barack Obama.",
         "read_more": "Biography.com: https://shorturl.at/jvLg7;",},
        {"image_path": "dream_team.png", "year": 1992, "title": "The Dream Team Dominates the Olympics",
         "short_description": "A team of NBA legends, including Jordan, Magic, and Bird, crushes the competition in Barcelona.",
         "title_one": "History",
         "text_one": "In 1989 FIBA, the international basketball governing body, voted to allow professional players to compete in the Olympics. Previously, competition was limited to amateur players, and the U.S. men’s teams had been primarily made up of college athletes. Over the years, however, multiple countries found loopholes to skirt the rule, allowing their best players to play on their teams. The 1989 decision was seemingly made to level the playing field. The U.S. men’s Olympic basketball team was thus able to bring together some of the top stars from the NBA to compete in the 1992 games.",
         "title_two": "The superheroes are in town",
         "text_two": "The world stood still as the USA basketball team was announced for the Barcelona 1992 Olympics. For the first time in Olympic history, the United States team would feature active NBA stars Michael Jordan, Magic Johnson and Charles Barkley. They became known as the ‘Dream Team’ defeating their opponents by an average of 44 points en route to the gold medal, as they went undefeated in eight games at the Summer Olympics.",
         "title_three": "Into the legend",
         "text_three": "Of the twelve players on the team, ten were named in 1996 among the 50 Greatest Players in NBA History, the official list of the 50 greatest players of the league's first 50 years. The USA team was so much better than the competition that head coach Chuck Daly did not call a single timeout during the tournament. Michael Jordan and Scottie Pippen became the first players to win both NBA championship and Olympic gold medal in the same year, having played for the Chicago Bulls.",
         "title_four": "Roster",
         "text_four": "The roster of what has been called the greatest sports team ever assembled included Michael Jordan (Chicago Bulls), Larry Bird (Boston Celtics), Magic Johnson (who had retired from the Los Angeles Lakers in 1991 after being diagnosed with HIV, the virus that causes AIDS), Charles Barkley (Phoenix Suns), and Scottie Pippen (Chicago Bulls). Christian Laettner (Duke University Blue Devils) was added as the sole college player instead of Shaquille O’Neal, who at the time played on the Louisiana State University Tigers (O’Neal later played on the U.S. men’s team at the 1996 Games in Atlanta). Chuck Daly, the Detroit Pistons coach, was selected as the head coach.",
         "read_more": "Olympics.com: https://shorturl.at/YcBV5; Britannica:https://shorturl.at/9yFPe",},
        {"image_path": "kobe_ai.png", "year": 1996, "title": "Kobe Bryant & Allen Iverson Join the NBA",
         "short_description": "Two of the league’s biggest stars enter the NBA straight from high school and college, shaping the future of the game.",
         "title_one": "Description",
         "text_one": "Allen Iverson and Kobe Bryant are arguably the most prolific players from the stacked 1996 Draft class. Some say Steve Nash belongs up there with them, but A.I. and Kobe are popular choices for the most part. Since they grew up in the league simultaneously, they had a natural rivalry, especially when they clashed in the 2001 NBA Finals. Alongside that rivalry, Iverson and Bryant had mutual respect as they pushed each other to become better players.",
         "title_two": "Kobe and A.I. knew how to motivate each other",
         "text_two": "As the two superstars to emerge from the 1996 Draft, both players were under pressure to deliver. Iverson had an impressive start, winning Rookie of the Year for the 1996/97 season. He was stellar in that first year, averaging 23.5 points and dishing out 7.5 assists per game. A.I. was phenomenal, even crossing over Michael Jordan in a game against the Bulls. Bryant struggled during his rookie year, only scoring 7.6 points per game. That was a big reason behind his work ethic for the rest of his career, as his first year was full of lessons and criticism. From his second year onwards, Kobe was an All-Star player who kept improving to meet his superstar potential.",
         "title_three": "",
         "text_three": "Their top-tier performances in almost every game helped motivate the other. They might not have been competing with each other, but they always wanted to be the best in the league, let alone their draft class. Iverson considers Kobe the ultimate competitor because he learned Bryant always wanted to know how Allen works. 'A.I., as a competitor, he drove me to be more obsessive about the game because I had to figure out how to solve that problem,' Kobe said in a press conference during the 2016 All-Star Weekend. 'I told him, I saw him this weekend, 'You don't realize how much you pushed me. I don't think people nowadays realize how great you were as a player, how big of a problem you were for defenses.'",
         "title_four": "Both players became all-time greats",
         "text_four": "With the two players becoming more involved in their teams' chances of winning silverware after their rookie years, only Kobe won championships. He won five of them, while A.I. could not win one. Iverson came close by carrying a mediocre 76ers team to the Finals. Still, they could not get past a Black Mamba and Shaquille O'Neal-powered team. Despite A.I.'s lack of a title, he is still a legend. The Georgetown product is considered one of the most influential players ever due to his stellar play at 6'0' and how relatable he was to the common folk watching the game. On the other side, Kobe won everything there is to win in basketball. At the same time, he is influential due to his Mamba Mentality. They made each other better, and that should keep happening to players from the same draft classes.",
         "read_more": "basketballnetwork.com: https://shorturl.at/eETyk, https://shorturl.at/yw8is ",},
        {"image_path": "legoat.png", "year": 2003, "title": "LeBron James Gets Drafted",
         "short_description": "LeBron James is selected first overall by the Cleveland Cavaliers, marking the start of a new era.",
         "title_one": "Biography",
         "text_one": "LeBron James is universally regarded as one of the greatest NBA and basketball players of all time. The debate on whether he is the best has raged on among basketball fans, with arguments that could sway in either direction. Born in Akron, Ohio, LeBron Raymone James attended St. Vincent-St. Mary High School in his hometown. LeBron led his High School to 3 state championships and was named the consensus 2003 National High School Player of the Year. He was PARADE magazine’s High School Boys Player of the Year as both a junior and senior to become the first repeat winner. He won Ohio’s Mr. Basketball Award his final three seasons, becoming the first sophomore to earn the honor. He also played football in high school through his junior year, and was named First Team All-State as a wide receiver his sophomore year.",
         "title_two": "When was LeBron James drafted?",
         "text_two": "Following his illustrious high school career, James was selected as the first overall pick in the 2003 NBA draft by the Cleveland Cavaliers. Wearing the iconic 23 jersey made famous by Michael Jordan, he soon claimed the Rookie of the Year award after his first full season in the NBA and represented the USA at the Athens 2004 Olympic Games, winning a bronze medal. He was believed to be a generational talent who could eventually develop into the face of the NBA. More than 20 years later, James has lived up to those expectations. He has won four championships with the Heat (two), Cavaliers (one) and Lakers (one) while rivaling Michael Jordan as one of the best and most successful players in NBA history.",
         "title_three": "",
         "text_three": "In short, the 6-foot-9 (2.06m) athlete rapidly established himself as one of the premier players in the NBA after his Olympic debut in Greece. During an impressive seven-season stint with the Cavaliers (averaging 78 games player per season), the forward amassed numerous individual accolades, including the NBA Most Valuable Player (MVP) award, although the coveted championship still eluded him.",
         "title_four": "Professional Career Achievements",
         "text_four": "LeBron is the NBA’s all-time leading scorer. He is a four-time NBA Champion (2012, 2013, 2016, 2020); four-time NBA MVP (2009, 2010, 2012, 2013); four-time NBA Finals MVP (2012, 2013, 2016, 2020); NBA Rookie of the Year (2003) and unanimous All-Rookie First Team Selection (2003); Team USA Olympic Gold Medalist (2008 Beijing, 2012 London, 2024 Paris); 20-time All-NBA Honoree; 6-time NBA All-Defensive Team; starter for NBA All-Star Game each of the last 20 seasons (2005-2024); and 3-time All-Star Game MVP (2006, 2008, 2018). He has appeared in 1,492 NBA games (1,490 starts) for the Lakers, Cavaliers, and Heat. LeBron has the most assists among all frontcourt players in NBA history. In 1,484 games he has scored in double figures, including an NBA-record 1,222 consecutive times, a streak that began on January 6, 2007. He has scored 20+ points in an NBA-record 1,237 games, 30+ in 555 games, 40+ 77 times, 50+ in 14 games and one 60-point game. Over his career, he owns 112 triple-doubles and 572 double-doubles. In an NBA-record 20 consecutive seasons, he has averaged at least 25.0 points. LeBron has appeared in 287 playoff games (all starts) for the Lakers, Cavaliers, and Heat, averaging 28.4 points, 9.0 rebounds, 7.2 assists, 1.7 steals, and 1.0 blocks in 41.3 minutes. He is the NBA Playoffs all-time leader in wins (183), games played (287), points (8,162), field goals (2,928), free throws (1,836), steals (483) and minutes (11,858). He has won an NBA-record 41 career playoff series and played in 8 consecutive NBA Finals (2011-2018).",
         "read_more": "Olympics.com: https://shorturl.at/YLyAw; NBA.com: https://shorturl.at/JHlSv; sportingnews.com: https://shorturl.at/7iC2f;",},
        {"image_path": "kobe_81.png", "year": 2006, "title": "Kobe’s 81-Point Game",
         "short_description": "Kobe Bryant scores 81 points against the Raptors, the second-highest in NBA history.",
         "title_one": "Kobe Bryant drops 81 points on Raptors in 2006",
         "text_one": "When Wilt Chamberlain scored 100 points against the New York Knicks on March 2, 1962, the NBA world knew it would never see anything like it again. The fact that there were no television cameras to capture the event only added to the legend of the performance. Since that game, the 70-point margin had been crossed six times and just twice since 1963, but that was as far as it went. It seemed David Robinson’s 71-point game in 1994 against the Clippers was as high as anyone would ever reach again. That was until Kobe Bryant burned the Toronto Raptors on January 22, 2006 in one of the greatest single-game performances in NBA history. Everyone can remember what they were doing the night Los Angeles Lakers legend Kobe Bryant scored 81 points, leading the team to a 122-104 comeback win over the Toronto Raptors. Bryant finished with 81 points on 28-of-46 shooting, including 7-of-13 from 3-point range, and 18-of-20 from the foul line. The accomplishment stunned even Bryant himself.",
         "title_two": "",
         "text_two": "“Not even in my dreams,” Bryant said. “That was something that just happened. It’s tough to explain. It’s just one of those things. 'It really hasn’t, like, set in for me. It’s about the `W,’ that’s why I turned it on. It turned into something special. To sit here and say I grasp what happened, that would be lying.' In a season Bryant led the league in scoring with 35.4 ppg, his game against Toronto had even the most seasoned NBA observers starstruck. Teammates and staff alike were asking Bryant to autograph copies of the box score after the game. Lakers public address announcer Lawrence Tanter was telling fans to save their ticket stubs. Then-Lakers owner Jerry Buss described the game as “like watching a miracle unfold.”",
         "title_three": "",
         "text_three": "But it was perhaps Lakers coach Phil Jackson, who’d spent nearly a decade coaching Michael Jordan, that put the performance in its proper perspective. 'That was something to behold,' Jackson said. 'It was another level. I’ve seen some remarkable games, but I’ve never seen one like that before.'",
         "title_four": "Kobe Bryant prefers 81-point performance over final game",
         "text_four": "Bryant had countless memorable games throughout his career, but perhaps the two that stand above the rest were when he scored 81 points against the Raptors and then when he scored 60 in the final game of his career. When asked which one he prefers, Bryant took the 81-point game, which isn’t a surprise considering that is when he was at the peak of his powers. When Bryant scored his final two points on a pair of free throws with 43.4 seconds remaining, the chants of “M-V-P! M-V-P!” from the 18,997 fans at Staples Center couldn’t have been more fitting. Bryant finished the second half scoring 55 of his 81 points — the second highest point total in a half in NBA history behind Chamberlain’s 59-point second half in his 100-point game.With his team trailing by 18 points in the third quarter, Bryant simply exploded, scoring 27 points in the third and 28 in the fourth. He accounted for all but 18 of the Lakers points in the second half and single-handedly put the game away. Bryant was hitting shots from all over the court, nailing contested jumper after contested jumper, leaving the Raptors without answers. 'We were just watching him shoot,' said Toronto forward Chris Bosh. The Raptors weren’t the only one’s watching. As Bryant would later note, his 81-point game was the first and only professional game his grandmother had ever seen him play live. She picked the right one.",
         "read_more": "NBA.com: https://shorturl.at/mmqi5; lakersnation.com: https://lakersnation.com/this-day-in-lakers-history-kobe-bryant-scores-81-points-against-raptors/",},
        {"image_path": "73_wins_warriors.png", "year": 2016, "title": "Warriors' 73-9 Season",
         "short_description": "Golden State breaks the regular-season win record, but LeBron James leads Cleveland to a historic 3-1 Finals comeback.",
         "title_one": "",
         "text_one": "The Golden State Warriors entered the 2015-16 season as a rare breed — defending champions with a chip on their shoulders. The team eliminated LeBron James and the Cleveland Cavaliers in the 2015 NBA Finals to win the franchise’s first NBA championship since 1975. But injuries to Kyrie Irving and Kevin Love allowed some to discredit Golden State’s accomplishment. The Warriors were determined to make it clear in ‘15-16 that their team was a legitimate champion. The Warriors’ quest began without their coach, Steve Kerr, who was sidelined due to debilitating migraines caused by an offseason operation on his back. Assistant coach Luke Walton replaced Kerr to start the season and the Warriors responded in a big way.",
         "title_two": "",
         "text_two": "The Warriors began the season with an unbelievable 24-game winning streak. Led by Stephen Curry and Klay Thompson, Golden State scored 100-plus points in every game during this streak and excelled with an undefeated target on their back. The team finally lost on Dec. 12 to the Milwaukee Bucks, 108-95. The Warriors’ 24-0 start shattered the previous NBA record for undefeated start to a season, a 15-0 mark the Houston Rockets (1993-94) and Washington Capitols (1948-49) both shared. Despite the end of their streak, the winning continued for Golden State. When Kerr returned to the sidelines on Jan. 22 after 43 games, the team sat in first place with a record of 39-4. At this point in the season, the Chicago Bulls’ NBA record of 72 wins in 1995-96 was well within sight for the Warriors.",
         "title_three": "",
         "text_three": "The season was filled with memorable games for Curry and the rest of the Warriors. Curry scored more than 45 points in six games, including a remarkable 46-point performance against the Oklahoma City Thunder. In that game, Curry made 11 3-pointers, had six assists and the game-winning shot at the buzzer to win the game in overtime. That was Golden State’s 28th road win, which set a franchise record. Overall, the team finished with an NBA-record 34 road wins.",
         "title_four": "",
         "text_four": "The 2015-16 Warriors etched their placed in history when, with a 125-104 victory over the Memphis Grizzlies on April 13, 2016, they captured their 73rd win of the season. The 73-9 record broke the NBA’s single-season wins record previously held by the 1995-96 Chicago Bulls (72-10). Though the feat set new heights for future teams to reach, the Dubs accomplished more than just one season-long record. Through the 2015-16 season, the team broke a variety of NBA team records, individual player records, and franchise records all while accomplishing a number of NBA “firsts.”",
         "read_more": "NBA.com: https://shorturl.at/ieFAf, https://shorturl.at/n3Zzu",
         },
        {"image_path": "coachs_challenge.png", "year": 2018, "title": "NBA Expands Coach’s Challenge",
         "short_description": "For the first time, coaches can challenge referee calls, adding a new strategic element to the game.",
         "title_one": "",
         "text_one": "The Coach’s Challenge affords head coaches the ability to trigger instant replay review on a limited set of matters, giving them a voice and furthering engagement while optimizing the overall replay process. 'Our coaches were receptive to the pilot version of the Coach’s Challenge, increasing usage and becoming more comfortable with the concept and strategic aspects as the season progressed,” said Byron Spruell, NBA President, League Operations. “We are excited to adopt the Coach’s Challenge as part of our NBA rules and will continue dialogue with the coaches, the Competition Committee and the NBA’s Board of Governors as we move forward.”",
         "title_two": "",
         "text_two": "The Board also approved language to clarify two specific situations: 1. A team loses its right to challenge the preceding call if it incurs a delay of game violation prior to initiating the challenge; 2. When officials confer to determine the appropriate call, the window of time within which a team must “immediately” challenge the call starts after the officials provide the negatively affected team notice of the final ruling on the play. During the 2019-20 season, NBA head coaches challenged 633 calls in the regular season and 67 in the playoffs. The original call on the floor was overturned 281 times in the regular season for an overturn rate of 44 percent. The overturn rate in the postseason was 40 percent with 27 calls reversed.",
         "title_three": "Key Features of the Coach's Challenge",
         "text_three": "Key features of the Coach’s Challenge are below: 1. Each team is entitled to one challenge in the game (regardless of whether the challenge is successful).; 2. A team can use its challenge in the following instances: a called personal foul charged to its own team; a called out-of-bounds violation; or a called goaltending or basket interference violation. — A team can use its challenge on a called personal foul at any point in the game. — In the last two minutes of the fourth period or the last two minutes of overtime, a called out-of-bounds violation or called goaltending/basket interference violation will not be challengeable and instead will be exclusively triggered by on-court referees.; 3. To initiate a challenge, a team must immediately call a legal timeout and the head coach must immediately signal for a challenge by twirling his/her finger toward the referees.; 4. If a team attempts to challenge an event with no remaining timeouts, the team is charged an excessive timeout, for which the penalty is a technical foul, and no challenge will take place.; 5. If a team calls a timeout to challenge an event that may not be reviewed, the team will be charged a timeout but retain its challenge.; 6. As with other replay reviews, in order to overturn the event as called on the floor, there must be clear and conclusive visual evidence that the call was incorrect.",
         "title_four": "NBA Replay Center Triggers",
         "text_four": "In the first 46 minutes of the game and the first three minutes of overtime, the NBA Replay Center will be able to trigger instant replay of the following events: 1. 2-Point or 3-Point Field Goals – i.e., whether a made field goal should count as two or three points or, in the event of a shooting foul, whether the offensive player should be awarded two or three free throws for being fouled on a shot attempt.; 2. Potential Shot Clock Violations – i.e., whether a successful field goal was attempted before or after the shot clock expired.; 3. A new “courtside administrator,” hired and supervised by the League Office, will be stationed at the scorer’s table to facilitate and expedite communication between the NBA Replay Center and the on-court referees. The courtside administrator will not have any decision-making authority with respect to officiating calls or replay determinations.; - The NBA’s Competition Committee recommended the two changes to the instant replay rules before the Board of Governors’ vote.",
         "read_more": "NBA.com: https://shorturl.at/Xma0z, https://shorturl.at/viSmQ, https://www.nba.com/news/nba-summer-league-2018-adding-coaches-challenge-option; official.nba.com: https://official.nba.com/rule-no-14-coachs-challenge/#:~:text=a.,%E2%80%9CChallenge%E2%80%9D%20for%20short).",},
        {"image_path": "lakers_championship.png", "year": 2020, "title": "NBA Bubble & Lakers Championship",
         "short_description": "The NBA creates a ‘bubble’ in Orlando due to COVID-19, where LeBron and the Lakers win the title.",
         "title_one": "The Bubble",
         "text_one": "The 2020 NBA Bubble was the bio-secure bubble at Walt Disney World in Bay Lake, Florida, near Orlando, that was created by the National Basketball Association (NBA) to protect its players from the COVID-19 pandemic during the final eight games of the 2019–20 regular season and throughout the 2020 NBA playoffs. Twenty-two out of the 30 NBA teams were invited to participate (the other eight had been eliminated from playoff contention) with games being held behind closed doors at the ESPN Wide World of Sports Complex and the teams staying at Disney World hotels. The bubble was a $190 million investment by the NBA to protect its 2019–20 season, which was initially suspended by the pandemic on March 11, 2020. The bubble recouped an estimated $1.5 billion in revenue. In June, the NBA approved the plan to resume the season at Disney World, inviting the 22 teams that were within six games of a playoff spot when the season was suspended. The plan initially received a mixed reaction from players and coaches.",
         "title_two": "",
         "text_two": "After playing three exhibition scrimmages inside the bubble in late July, the invited teams played eight additional regular season games to determine playoff seeding.[4][5] The playoffs began on August 17, and the NBA Finals began on September 30. During the playoffs, there were additional delays to the season prompted by activism related to the shooting of Jacob Blake. The season ended on October 11 when the Los Angeles Lakers defeated the Miami Heat in six games. From the start of the resumed 2019–20 season until the end of the NBA Finals, the NBA ended with no recorded cases of COVID-19 for the teams participating in the bubble. The NBA Bubble in some form has been made into a contingency plan for the NBA in future pandemics or major disease outbreaks.",
         "title_three": "The Championship",
         "text_three": "The 2019–20 Los Angeles Lakers season was the franchise's 72nd season, its 71st season in the National Basketball Association (NBA), and its 60th in Los Angeles. The Lakers were coached by Frank Vogel in his first year as team head coach. The team played its home games at Staples Center as members of the Western Conference's Pacific Division. The team dedicated the season to retired Lakers superstar Kobe Bryant, who was killed in a helicopter crash on January 26, 2020. On March 6, 2020, the Lakers clinched their first playoff berth since the 2012–13 season. Five days later, due to the ongoing COVID-19 pandemic, the season was suspended. On July 5, the NBA announced a return of the season in the NBA Bubble, with 22 teams playing eight seeding games followed by a full postseason. Play resumed on July 30, with all games being played in Orlando, Florida. On August 3, the Lakers clinched the top seed in the Western Conference playoffs for the first time since the 2009–10 season.",
         "title_four": "",
         "text_four": "The Lakers finished the shortened season 52–19, with a winning percentage roughly equivalent to 60 wins in a full season. They defeated the Portland Trail Blazers, Houston Rockets, and Denver Nuggets to advance to the NBA Finals. There, they defeated the Miami Heat (LeBron James' former team) in six games to earn the franchise's 17th NBA championship. The Lakers also became the first and only team in NBA history to be undefeated in a season when leading entering the fourth quarter, going a combined 57–0 record in the regular season and playoffs.",
         "read_more": "Wikipedia: https://shorturl.at/KX9pu, https://shorturl.at/8N5uc",},

    ]

    for event in events:
        db.session.add(Event(**event))

    db.session.commit()

    admin_user = User("jordan.png", "admin", "Dachi", "Nioradze", "dachi.nioradze.gmail.com", "adminpassword123", "admin")
    db.session.add(admin_user)
    db.session.commit()



    lekso_post = ReadPost(title="Interview With Lekso Khinchagashvili",
                          text="What are the most important skills that new players should work on improving? - Of course, the 3 basic components of basketball for beginners (from my own experience with children) are shooting, dribbling and passing.;"
            "What role does discipline play in developing a successful basketball player? - I think discipline is essential for a basketball player and for any person in general. Therefore, I think that what an athlete does off the court has a great influence on his success.;"
            "What attitude should players have toward practice and games? How should players deal with failure, loss, or poor play? What advice do you have for players who are struggling with motivation or self-confidence?- Practice how you play is one of my favorite phrases, I understand that sometimes 8-9 workouts a week are too tiring, but I think otherwise, success is impossible to achieve, I advise players who lack motivation to never give up, because hard work always brings results;"
            "What should players consider to prevent and recover from injuries? How important is nutrition in basketball and what should they pay attention to before/after practice? - Injury is a friend of basketball players, the main thing is proper nutrition, proper training, and in this way you can greatly reduce the chance of getting injured;"
            "How can a player improve their decision-making skills and basketball IQ? - One of my favorite types of exercises is Read and React, when a player has to analyze the actions of a defender and then make a decision. I think such exercises help improve decision-making. Also exercises with advantage (2v1 3v2)."
            "What is the one piece of advice every young player should know? - Always fight for your goals, you can do anything!"
            "What separates a great player from an average one? - A player who has progressed."
            "Have you ever seen a player who has made significant progress over time? What did they do differently? - I have seen many players who have achieved a lot in a very short time with selfless work, the main thing is never to stop", target="Other", author_username = "admin", author_first_name="Dachi", author_last_name="Nioradze", author_profile = "jordan.png")
    db.session.add(lekso_post)
    db.session.commit()

    maisa_post = ReadPost(title="Interview With Irakli Maisuradze",
                          text="He was asked to share any type of infromation he thought would be useful for basketball players to hear. Meaning, to help them on their jorney to achieving their goals. This is what he had to say.: "
                               "Basketball has five main options: 1) Dribbling 2) Drive to the basket 3) Passing 4) Defense 5) Shooting. It's preferable that a kid start to learn the game of basketball with these main options. It starts with dribbling. Its very important to be able to dribble without looking at the ball, as in basketball it's often required to complete a couple of these options at once - dribbling and driving, then dribbling and passing and so on (after you learn how to dribble, you move onto these). After that, it's better to make the kid comfortable with protecting their basket and playing physical defense."
                               "Logically, here comes the footwork. 1) Parallel Steps 2) Back Steps 3) Close Out 4) Switch, as these are the main defensive options that any kid interested in basketball should know. For shooting, things are a little bit different. It's very specific, varying person to person, and therefore requires the most attention and correcting from a coach."
                               "The reason is that a small child, does not have enough power to handle the ball and shoot it with correct form. Hence, they tend to shoot the ball extremely inccorectly and inefficiently. At that moment, it's important that we first teach them how to hold the ball."
                               "The ball should be place on the fingers, and not the palm of the hand. Then we should focus on the positioning of elbow and the wrist, as during the moment of the shot, the arm should be above the head and the wrist bent (closed). We should hold this positing until the end of the shot."
                               "The main mistake everybody makes is rushing through the process. Everybody tries to be the leader from the start, a have this 'cool' image, to be the leading player, but unfortunately, that's not how it works. Every player requires paying attention to detail at a high level, because at the next level, playing at high speeds, all of the ingnored things start showing up as cruical mistakes."
                               "About working outside the court, imagine this: there are many players at practice that want to be great, but some are more talanted and quickly get what the coach is asking, but for some it takes time. So it's significant that you think about this outside of practice - it rquires analysis. It's more advisable to practice what you learn by yourself. Go find an empty court and work on yourself, to better the skills and master the technical/tactical aspects of basketball."
                               "Another important thing is discipline. Every player, in every practice or game, should be extremely concentrated, as the game is dependant on time. You have a defined number of seconds for both defense and offense. To think critically at a fast pace and analyze the game, it requires a developed mind ( basketball IQ ), which everyone can develop - the main thing is to learn, practice and not be lazy."
                               "This leads us to dealing with failures. At the starting stage, we should teach players that this is just another game - that you cannot always win. Of course, experiencing failures and setbacks can be challening but it's our duty as coach's to learn from our mistakes, why we lost, what could have gone better and so on. It's also on us to make the players understand, not by fighting, but by talking and explaining, and to help them improve on what they're lacking, to teach them to play as a team, to eventually achieve victoey as well."
                               "In short, everything comes from the mind. Imagine, you're seeing with your eyes hearing with your ears, then analyzing that information with your brain and then you start to take action. All of these are based on discipline and on how organized you are. The only thing that turns talent into a legend is hard work and learning. Otherwise, that is just unimaginable. ", target="Other", author_username = "admin", author_first_name="Dachi", author_last_name="Nioradze", author_profile = "jordan.png")

    db.session.add(maisa_post)
    db.session.commit()


    test_post = ReadPost(title="My experience With Nutritioning", text="Basketball is a high-intensity sport that calls for both mental and physical agility. Basketball players have significant energy needs during the season, which could increase even more during off-season training. Speaking from experience, I know it can be difficult to choose foods that will give you the energy you need for training and competition. Smaller college players and high school athletes have varying access to resources, in contrast to elite college or professional basketball players who have the resources and opportunity to eat a healthy diet. This is exactly what I struggled with and here's what helped me get through it."                                                                 ""
    "At one point, I wasn’t eating enough to match the amount of energy I burned during games and practices. I’d feel sluggish by the second half of games, and my legs would feel heavy. It took me a while to understand that basketball requires a lot of fuel, and I had to be intentional about eating more than just what 'felt right.' When I started increasing my food intake, I felt a huge difference in my endurance, but keep in mind, only after about a couple of weeks. Don't expect to have a huge surge of energy after a few days."
    "I used to think that the most important thing for an athlete was protein, but I've since learned that carbohydrates are just as important, if not more so. I would quickly become exhausted if I wasn't eating enough carbohydrates. Increasing the amount of bread, pasta, rice, and fruits in my meals was what changed things for me. Even if it was just a banana or a piece of toast, I would make sure to eat something before an early morning practice."
    "Speaking about protein, I had previously believed that protein was only necessary for muscle growth, but I have since come to understand that it is also crucial for recovery. I tried to eat meals that included chicken, eggs, yogurt, or a protein shake after big workouts. As a result, I felt less sore and more ready for the next session, which to be honest, impacted my mood as well for the better."
    "Before games, I experimented with different meals to see what made me feel the best, but I found out a light snack, like a banana or an apple, was the best."
    "To sum up, figuring out the right nutrition for basketball wasn’t easy, and I had to learn a lot through trial and error. I didn’t have a dietitian guiding me, but by paying attention to how my body responded to different foods, I found what worked. Every player is different, so it’s important to experiment and listen to your body. If you’re struggling with energy levels, recovery, or endurance don't give up just yer, as making small changes in your diet might make a bigger difference than you expect.",target="Nutritioning, Recovery & Physical Health", author_username="admin", author_first_name="Dachi", author_last_name="Nioradze", author_profile="jordan.png")
    db.session.add(test_post)
    db.session.commit()

    test_post_2 = Post(image_path="fadeaway.png", title="The Art of the Fadeaway: Mastering One of Basketball’s Toughest Shots", description="The Art of the Fadeaway: Mastering One of Basketball’s Toughest Shots The fadeaway is one of the most difficult yet effective shots in basketball. Popularized by legends like Michael Jordan and Kobe Bryant, this move allows players to create space and shoot over defenders with ease. But executing a perfect fadeaway takes more than just jumping backward—it requires balance, control, and hours of practice. Here’s how to master it: 1) Footwork is Key – Start with a strong base, pivot on your back foot, and push off with your front foot as you lean back. 2) Stay Balanced – Keep your shoulders squared to the hoop, even as your body drifts away. 3) Perfect the Release – Shoot at the highest point of your jump with a soft touch and follow-through. 4) Repetition & Strength Training – Strengthen your core and legs to improve control over your fadeaway. A well-executed fadeaway can make you unstoppable in one-on-one situations. Just remember: the more you practice, the more natural it becomes. Who’s your favorite fadeaway shooter? Let me know in the comments!", target="Shooting", author="admin", author_profile="jordan.png")
    db.session.add(test_post_2)
    db.session.commit()

    test_post_3 = Post(image_path="injury.png",
                       title="Injury Prevention: How to Stay in the Game Longer",
                       description="Basketball is fast, physical, and demanding. The last thing any player wants is an injury that keeps them off the court. Whether you’re a casual hooper or a competitive athlete, taking care of your body is crucial. Here are 5 key injury prevention tips: 1) Warm-Up Properly – Dynamic stretching and mobility drills prepare your body for explosive movements. 2) Strength & Conditioning – Building strong legs and a stable core helps absorb impact and prevent knee injuries. 3) Ankle Stability – Wear supportive shoes, practice balance drills, and tape your ankles if needed. 4) Listen to Your Body – Pushing through pain can turn small issues into major injuries. Rest and recover when needed. 5) Post-Game Recovery – Cool down, stretch, and ice sore muscles to reduce inflammation. Injuries can happen, but smart training and preparation minimize the risks. What’s the worst injury you’ve ever had on the court? Drop a comment below!",
                       target="Health, Nutritioning & Recovery", author="admin", author_profile="jordan.png")

    db.session.add(test_post_3)
    db.session.commit()

    test_post_4 = Post(image_path="shooting_off_the_dribble.png",
                       title="Off-the-Dribble Shooting - Become a More Dangerous Scorer",
                       description="Some of the best scorers in basketball—Kyrie Irving, Stephen Curry, and Damian Lillard—aren't just great at shooting; they’re elite at shooting off the dribble. Unlike catch-and-shoot players, those who master this skill can create their own shot in any situation, making them nearly impossible to guard. But what does it take to knock down shots off the dribble consistently? Master Your Balance & Footwork: Shooting off the dribble means transitioning from motion to a stable shooting stance in a split second. To do this effectively: 1) Stay Low – Keep your knees bent while dribbling to maintain control and explode into your shot. 2) One-Two or Hop? – Some players prefer a one-two step into their shot, while others hop into it. Test both and see what works best. 3) Shoot Off Different Angles – Practice pull-ups from the top of the key, wings, and baseline so you’re comfortable from anywhere. Work on a Quick & Fluid Release: Defenders won’t give you much time to get your shot off, so your release needs to be quick and controlled. Here’s how: 1) Minimal Gather Time – Eliminate extra motion in your shooting form. Go straight from the dribble into your shot. 2) High & Consistent Release – Aim to shoot over your defender’s reach, making it harder to contest. 3) Use the Off-Hand Wisely – Your guide hand should only stabilize the ball—don’t push with it. Build Confidence Through Reps: The best way to become automatic off the dribble? Repetition. 1) Drill 1: Dribble-Pull-Up (Mid-Range & Three-Point) – Take one hard dribble and rise into your shot. Work on both hands. 2) Drill 2: Stepbacks & Side Steps – Create separation and shoot. Focus on balance! 3) Drill 3: Game-Speed Shots – Simulate real-game situations by adding defenders or shooting under pressure. When you get comfortable shooting off the dribble, defenders will have to play you differently—opening up driving lanes and passing opportunities. Who’s your favorite off-the-dribble shooter? Let’s talk in the comments! ",
                       target="Shooting", author="admin", author_profile="jordan.png")

    db.session.add(test_post_4)
    db.session.commit()

    test_post_5 = Post(image_path="strength_and_conditioning.png",
                       title="Strength & Conditioning: Why It’s a Game-Changer for Basketball Players",
                       description="You don’t have to be the biggest or strongest player on the court, but if you want to be quicker, more explosive, and less injury-prone, strength training is non-negotiable. Many young players avoid lifting weights because they fear it will make them 'too slow' or 'too bulky'—but the truth is, a proper strength & conditioning program will only make you better. The Key Benefits of Strength Training for Basketball: 1) Increased Power & Explosiveness – Strength training improves your vertical jump, sprint speed, and agility. 2) Better Endurance & Stamina – Stronger muscles don’t tire as quickly, allowing you to play harder for longer. 3) Injury Prevention – A well-conditioned body absorbs impact better, reducing the risk of sprains, tears, and fractures. 4) More Confidence in Physical Matchups – You’ll finish through contact, hold your ground on defense, and dominate rebounds. How to Train for Strength Without Losing Speed: Your workouts should focus on building functional strength, not just lifting heavy. Here’s a balanced approach: 1) Lower-Body Strength – Squats, lunges, and deadlifts build a strong base for explosive movements like jumping and cutting. 2) Core Stability – Planks, Russian twists, and medicine ball throws improve balance and body control. 3) Upper-Body Power – Push-ups, pull-ups, and dumbbell presses help with finishing around the rim and absorbing contact. 4) Plyometrics & Agility Drills – Box jumps, ladder drills, and sprints develop quickness and explosive movement. Recovery is Just as Important as Training: Muscles grow outside the gym, not during workouts. That’s why recovery is key: 1) Stretch & Foam Roll Daily – Prevent stiffness and improve mobility. 2) Eat the Right Foods – Fuel your body with lean protein, complex carbs, and healthy fats to build muscle and sustain energy. 3) Get Enough Sleep – Lack of sleep can slow muscle recovery and impact performance. Aim for 7-9 hours per night. Basketball is a physically demanding sport, and the stronger you are, the better you’ll perform. If you're not already incorporating strength training into your routine, now is the time to start!",
                       target="Skills & Performance", author="admin", author_profile="jordan.png")

    db.session.add(test_post_5)
    db.session.commit()